### ISSUE TITLE
loop scanning file 

### ISSUE THREAD

**Issue by dlnraja** [jamesbrindle/YTMusicUploader#14]
The software is allways scanning....

Io error path ... 
loop scan. no upload

https://i.imgur.com/gBKf8yG.png

**Comment by jamesbrindle** [comment]
Hey, thanks for that.

Would you like to give this version a try: https://github.com/jamesbrindle/YTMusicUploader/releases/tag/v1.5.2

Also, with that error, it looks as though the file path wasn't correct? Can you confirm that folder hasn't been moved?

Regards,

J

**Comment by dlnraja** [comment]
Yes it's right . Could you just implement a skipper to skip this file . 

Best regard

**Comment by jamesbrindle** [comment]
Hey,

The application should skip skip a watch folder if you've added a watch folder and it's since been removed and also tell you in the status bar. Also, during scanning or uploading a file it should also skip the file.

Has the 'looping' symptom stopped for you in the new version or is this still happening?

Kind regards,

J

**Comment by dlnraja** [comment]
On the latest version . It's looping the same subfolder . Imposible to add an subfolder exception.

Today I delete the software of my computer . 

Malwarebytes detects that's there is a malware inside this soft 

Best regard.

**Comment by jamesbrindle** [comment]
Hmm, impossible to add subfolder? I wonder... Will keep looking.

I'm sorry the software didn't work out for you. I'm not sure why Malwarebytes is detecting malware, I can assure you there isn't any... The source code is freely available in this repository... It maybe because the software is not signed? Which I don't ideally indent to do to be fair unless I can get a certificate free of charge... This application was just indented to be a small pet project for myself but ended up sharing it with others for free just in case anyone was interested but no other developers have shown much interest so the support is quite limited at this present moment.

Thanks for your input though I do really appreciate you taking the time to inform me of the issues.

**Comment by jamesbrindle** [comment]
Unable to replicate - No other reports.
