### ISSUE TITLE
GetResultCore Critical Error

### ISSUE THREAD

**Issue by frehder** [jamesbrindle/YTMusicUploader#16]
**Description**
Yesterday I installed YTMusicUploader to upload my full library of 12916 songs. Installation and first sign in went fine. After adding my music folder it did nothing, therefore I restarted the pc and then the upload startet. When I went to bed it had uploaded 7145 songs with 0 issues. I shut down the pc thinking it would pick up where it left.

Today I started the pc, checked if it is still logged in (it is) and since then (more than 4 hours ago) it sits there Idle "Looking for new files...".

I was curious if it was doing anything, therefore I looked in the Application Logs and saw an error which occurred when starting the pc/application (see below). I don't know if it just needs some time to compare which songs to upload or if the error prevents it from doing anything. 

Just wanted to report it because "Critical" error does not sound very healthy. ;) 

**Application Log**
LogTypeId: Critical
Source: GetResultCore
Message: `Main Process thread error: One or more errors occurred.`
Version: 1
StackTrace: 
```
at System.Threading.Task.Task`1.GetResultCore(Boolean waitCompletionNotification)
at YTMusicUploader.Business.FileScanner.Process()
at YTMusicUploader.MainForm.MainProcess(Boolean restarting)
```

**Versions**
YTMusicUploader v1.5.3
Windows 10 Pro v1909

**Comment by jamesbrindle** [comment]
Hey,

Unfortunately, it looks as though I haven't handled that particular exception very well, as it says 'One or more errors occurred'. I ideally need to exception message from 'within' the exception. Therefore I've made some changes in order to properly pinpoint where the exception is actually occurring...

However, I believe I can track where the exception has occurred down to 2 possible places.

1. Loading the database
2. Processing it's lists of uploads (uploading)

I've had a couple of reports where the database has become corrupt somehow, which isn't great I know.

Would you be able to try:

1. Completely exit the YT Music application
2. Completely delete the folder: %localappdata%\YTMusicUploader
3. Restart the application

This will effectively reset the application.

I'll work on making the DB more robust and generating better exception messages in the meantime.

Regards,

Jamie

**Comment by jamesbrindle** [comment]
Screw that... I think I've just found the issue. Will keep you posted on the new version...

**Comment by jamesbrindle** [comment]
New version uploaded: version 1.5.5

**Comment by frehder** [comment]
Thank you for the update. Version 1.5.5 did indeed fix the issue!
In the meantime I uploaded most of my music via the YT Music website. 
On the first launch of v1.5.5 it did a full comparison and uploaded only the songs that were missing. 
The application log does not contain any new errors.

Thank you very much!
