### ISSUE TITLE
no music files detected when folder is on a network file shares

### ISSUE THREAD

**Issue by foenyxxyneof** [jamesbrindle/YTMusicUploader#18]
I have my music in a folder on my Synology NAS and mounting the music folder using network file share under Windows 10. YTMusicUploader doesn't detect a file when using network file shares. Local disk folders are working fine.

**Comment by jamesbrindle** [comment]
Hey,

Are you sure? I seem to be unable to replicate the issue... Do you have specific permissions on your NAS for the network share? / Do you usually need to enter credentials in order to access the share?

[![N|Solid](https://portfolio.jb-net.co.uk/shared/network%20folder.png)](https://portfolio.jb-net.co.uk/shared/network%20folder.pn)

**Comment by foenyxxyneof** [comment]
Hi James,
my bad, you were absolutely right. It was indeed a NAS file permission issue and no issue on YTMuscicUploader. 
Thanks a lot for your cool tool.

**Comment by jamesbrindle** [comment]
Excellent! And you're welcome!
