### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by franklinkf** [jamesbrindle/YTMusicUploader#32]
I could not able to login. I followed the procedure. Everytime I am getting the message - Not authenticated - Try signing out and back in. Please Help.

Also can you share a sample playlist file for upload to know the pattern of the file?
 
![image](https://user-images.githubusercontent.com/8948123/135746888-6e2130fe-06bc-43e7-920b-2a3089f399cc.png)

**Comment by Aldaviva** [comment]
Hello,

I'm just guessing based on the instructions, since I stole my cookies from Vivaldi instead of Firefox, but the text above contains both request and response cookies, whereas the [video](https://youtu.be/ufuckGSathc?t=42) shows only copying the request cookies. From the video, you are supposed to right-click on one of the request cookie rows and choose "Copy All." This seems to copy properly for me in Firefox 92.0.1.

----

Specifically, the above text is a JSON object containing the two keys `"Response Cookies"` and `"Request Cookies"` whose values are objects, but this is too much, and only that second object should be included. So instead of looking like the following
```js
{
    "Response Cookies": {
        "name1": { /* cookie properties omitted */ },
        "name2": {}
    },
    "Request Cookies": {
        /* this is the object you want */
        "name3": {},
        "name4": {}
    }
}
```
it should just be
```js
{
    "name3": {},
    "name4": {}
}
```

**Comment by jamesbrindle** [comment]
Hey,

Thanks Aldaviva!

Yes, I don't think the app is able to parse the cookie text properly onto the desired request cookie object.

I do plan on making the parsing more lenient...

As for a playlist, a .m3u type playlist is quite common. You should be able to make one using most media player applications... iTunes, VLC, Windows media player...

Kind regards,

Jamie

**Comment by franklinkf** [comment]
Thanks Aldaviva & Jamesbrindle.  Followed the instructions shared by Aldaviva.  Got the validation successful.

Regarding .m3u playlist, let me try

Regards,

Franklin

**Comment by franklinkf** [comment]
Thanks.  Playlist upload also done

Thank you Jamesbrindle for this wonderful tool for music lovers

Regards

Franklin
