### ISSUE TITLE
500 Error from YT Music. Waiting 10 seconds then trying again (1/4)

### ISSUE THREAD

**Issue by eturk1** [jamesbrindle/YTMusicUploader#8]
First, thanks a BUNCH for creating this app. Bravo!!

Getting 500 error occasionally. 
Must kill app 

![image](https://user-images.githubusercontent.com/525280/96196200-a6a3c000-0f03-11eb-8915-063c8ec39740.png)

**Comment by jamesbrindle** [comment]
I'll fix that...

Uploading to YTmusic for some reason unknown to me occasionally responds with a 500 error. I've built in a workaround which will retry on failure (i.e your screenshot) but obviously something has gone wrong somewhere if it's become unresponsive at that stage.

I will fix it... Although I have struggled to do so as I'm unable to replicate myself. I'm effectively guessing, but I'll get to the bottom of it.

Thanks for reporting this.

Jamie

**Comment by eturk1** [comment]
Is there a way I can help you debug this, since I've got thousands of tracks to upload & it happens often?

Idea: maybe you could add a sort of debug console? Open up so finer messages about each step can be seen? Or, dumped to a txt file

**Comment by eturk1** [comment]
Just cloned from Git, running in VS. Keep getting exception at this location and this one shows the 500.

![image](https://user-images.githubusercontent.com/525280/96351011-a3c4de80-106d-11eb-8198-45e214136eb8.png)

**Comment by eturk1** [comment]
Just cloned from Git, running in VS. Keep getting exception at this location and this one shows the 500

![image](https://user-images.githubusercontent.com/525280/96351011-a3c4de80-106d-11eb-8198-45e214136eb8.png)

**Comment by jamesbrindle** [comment]
Hey pal, good work getting everything building! And you have indeed found the error. I have since fixed it in the new version 1.4.8: https://github.com/jamesbrindle/YTMusicUploader/releases/tag/v1.4.8 if you haven't already fixed it yourself. 

Regards,

Jamie

**Comment by jamesbrindle** [comment]
FYI. That's a pretty solid upload speed!

**Comment by eturk1** [comment]
BRAVO!! 
Figured out doing pull to update to 1.4.8. Seeing 500 errors on red status bar AND it recovers, continues.
-----------------
looks like it's throwing `Exception thrown: 'System.ArgumentException' in System.dll` when the 500 displays.
also see many `Exception thrown: 'System.ArgumentException' in System.dll`, esp. when first running
-----------------

on getting the code to run: 
LOL a bit rusty as I haven't coded regularly since the 90s
Seems doing "clean solution" on the main solution got me able to run the project

**Comment by jamesbrindle** [comment]
Hi,

You shouldn't really be seeing any exceptions? That's the plan anyway  Might be some more coding issues of mine... I'll certainly take another look and see what those exceptions.

Just t be clear... The displaying of the 500 error is by design. That's the error you're getting back from YouTube Music, not the app itself. And i have no control over it, other than to 'try again'. Seems to happen with lots of uploads in a short time.

There is another release ( installer ) on there you didn't have to pull and build it yourself  (unless of course you're having fun doing so).

Been thinking of adding a log of everything that the app is doing like you suggested. And either outputting it to a file or a separate database. Might come in handy. Cheers for the idea.... Obviously there is already an upload and an issues log but something more verbose might be better.

Also what you might notice if you're playing the the solution... I've made the UI forms inherit from an abstract form for code reusability. But I've noticed Visual Studio occasionally decides it doesnt want to show you the designer. Particular in x64 build mode... Bit odd... Might restructure that.

Cheers btw.
